/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This code was generated by avrogencpp 1.12.0-SNAPSHOT. Do not edit.*/

#ifndef IMAGE_SCHEMA_HH_1289654174_H
#define IMAGE_SCHEMA_HH_1289654174_H


#include <sstream>
#include <any>
#include "avro/Specific.hh"
#include "avro/Encoder.hh"
#include "avro/Decoder.hh"

namespace c {
struct imgsch {
    int64_t timestamp;
    std::string image;
    imgsch() :
        timestamp(int64_t()),
        image(std::string())
        { }
};

}
namespace avro {
template<> struct codec_traits<c::imgsch> {
    static void encode(Encoder& e, const c::imgsch& v) {
        avro::encode(e, v.timestamp);
        avro::encode(e, v.image);
    }
    static void decode(Decoder& d, c::imgsch& v) {
        if (avro::ResolvingDecoder *rd =
            dynamic_cast<avro::ResolvingDecoder *>(&d)) {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (std::vector<size_t>::const_iterator it = fo.begin();
                it != fo.end(); ++it) {
                switch (*it) {
                case 0:
                    avro::decode(d, v.timestamp);
                    break;
                case 1:
                    avro::decode(d, v.image);
                    break;
                default:
                    break;
                }
            }
        } else {
            avro::decode(d, v.timestamp);
            avro::decode(d, v.image);
        }
    }
};

}
#endif
